<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\CustomUserDiscounts\Controller\Admin\DiscountController' shared autowired service.

$this->services['PrestaShop\\Module\\CustomUserDiscounts\\Controller\\Admin\\DiscountController'] = $instance = new \PrestaShop\Module\CustomUserDiscounts\Controller\Admin\DiscountController(($this->services['PrestaShop\\Module\\CustomUserDiscounts\\Repository\\CustomUserDiscountRepository'] ?? $this->load('getCustomUserDiscountRepositoryService.php')), ($this->services['translator'] ?? $this->getTranslatorService()));

$instance->setContainer($this);

return $instance;
