<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.customuserdiscounts.module' shared autowired service.

return $this->services['prestashop.module.customuserdiscounts.module'] = \Module::getInstanceByName('customuserdiscounts');
