<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2asmiDK170W+pelHob7a'."\n".'vnVCVD3u2QmzxI/3yVmgLLGFps7pip1S5tNVqTM/3UrbsZnGyrx+MHg/w3ZQYTxW'."\n".'xefP+oVjZBLefB8JFXBDCBCt1E0b9nDvLDnQ9WACKsWWVhnqnesm4EVmDMDm0rnc'."\n".'DpM10SZb/16LEeamWj/MhK+kZrVjdfvK5qcCj5DJrvPK38lQIzpjFRA6S4GARwGz'."\n".'etPxMlv8zvn4b7arGBxKq/s/n89cPtFh40ap9nF6EMP45czdjDiUbwR84Pw8fJUF'."\n".'pJE4hShg9Ft3jfiAZ074LjkqwJRPMpoxsFiyJsSgBRQcJNBxtuMxChBss7Wydtb3'."\n".'aQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
