<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prestashop.module.customuserdiscounts.form.discount_type' shared service.

return $this->privates['prestashop.module.customuserdiscounts.form.discount_type'] = new \PrestaShop\Module\CustomUserDiscounts\Form\DiscountType(($this->services['translator'] ?? $this->getTranslatorService()), [0 => 'es-ES'], 'es-ES');
