<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.customuserdiscounts.controller' shared service.

$this->services['prestashop.module.customuserdiscounts.controller'] = $instance = new \PrestaShop\Module\CustomUserDiscounts\Controller\AdminCustomUserDiscountsController();

$instance->setContainer($this);

return $instance;
