<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNaYnYlh\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNaYnYlh/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNaYnYlh.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNaYnYlh\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerNaYnYlh\appAppKernelDevDebugContainer([
    'container.build_hash' => 'NaYnYlh',
    'container.build_id' => 'e9a63473',
    'container.build_time' => 1740078427,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNaYnYlh');
