<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXdLVIfO\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXdLVIfO/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXdLVIfO.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXdLVIfO\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerXdLVIfO\appAppKernelDevDebugContainer([
    'container.build_hash' => 'XdLVIfO',
    'container.build_id' => 'e7038bb1',
    'container.build_time' => 1740098465,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXdLVIfO');
