services:
  prestashop.module.customuserdiscounts.repository.discount_repository:
    class: PrestaShop\Module\CustomUserDiscounts\Repository\CustomUserDiscountRepository
    public: true
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  prestashop.module.customuserdiscounts.controller:
    class: PrestaShop\Module\CustomUserDiscounts\Controller\AdminCustomUserDiscountsController
    public: true
    parent: PrestaShopBundle\Controller\Admin\FrameworkBundleAdminController

  # Formulario de descuentos
  prestashop.module.customuserdiscounts.form.discount_type:
    class: PrestaShop\Module\CustomUserDiscounts\Form\DiscountType
    arguments:
      $translator: '@translator'
      $locales: ['es-ES']
      $defaultLocale: 'es-ES'
    tags:
      - { name: form.type }

  # Módulo principal
  prestashop.module.customuserdiscounts.module:
    class: CustomUserDiscounts
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'customuserdiscounts'